/**
 * Given two strings <tt>s</tt> and <tt>t</tt> which consist of only lowercase letters.
 * <p>
 * String <tt>t</tt> is generated by random shuffling string <tt>s</tt> and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in <tt>t</tt>.
 * <p>
 * <b>Example:</b>
 * <pre>
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 * </pre>
 *
 * @author Oleg Cherednik
 * @since 24.09.2020
 */
public class Solution {

    public static void main(String... args) {
        System.out.println(findTheDifference("abcd", "abcde")); // e
    }

    public static char findTheDifference(String s, String t) {
        char ch = t.charAt(t.length() - 1);

        for (int i = 0; i < s.length(); i++)
            ch ^= s.charAt(i) ^ t.charAt(i);

        return ch;
    }
}
